### ISSUE TITLE
fastqfilter step hangning when runnnin multiple alignements

### ISSUE THREAD

**Issue by jflucier** [erhard-lab/price#12]
Hi Florian,

still having problem on the fastqfilter step.

As you will see in the script below, I changed the alignement process so that every dependencies (Gedi, Reaper, R, bowtie, jdk, etc...) are copied locally to a compute node. 

When I execute 2 jobs, the fastqfilter message at beginning of execution outputs well:

`

[reaper] check 0 errors, 0 reads truncated, 50391296 clean, 0 lint, 50391296 total
2020-04-28 14:52:07.274 INFO Command: gedi -e FastqFilter -D -ld ERX609887.readlengths.tsv -min 18 ERX609887.
lane.clean
2020-04-28 14:53:09.195 INFO Discovering classes in classpath
2020-04-28 14:53:09.550 INFO Preparing simple class references
2020-04-28 14:53:09.829 INFO Gedi 1.0.2 (JAR) startup
2020-04-28 15:49:43.093 INFO Finished: gedi -e FastqFilter -D -ld ERX609887.readlengths.tsv -min 18 ERX609887
.lane.clean
aligning using bowtie on rrna

`

When I start 15 jobs, the log output hangs after te reaper execution:

`
[reaper] check 0 errors, 0 reads truncated, 144442614 clean, 0 lint, 144442614 total

`
been stuck at this log for more then an hour. When I run 2 jobs, this message appears within second / minutes.

When I look at the process on the compute node, it shows:

jflucier 25339  0.0  0.2 36534756 91492 ?      Sl   09:09   0:05 java -Xmx30g -Xms2048m -cp /localscratch/jflucier.5320192.0/ERX609888/programs/gedi/gedi.jar:/localscratch/jflucier.5320192.0/ERX609888/programs/gedi/lib/.* executables.FastqFilter -D -ld ERX609888.readlengths.tsv -min 18 ERX609888.lane.clean

As you can see, everything point to local drive /localscratch/jflucier.5320192.0/. This command is excuted in the /localscratch/jflucier.5320192.0 folder

Do you have an idea of what is going wrong? Can you briefly detail what this step does as I am thinking of rewriting it. Does it only filter the fastq for read size length and then plot graphs? 

When I look at the fastq code, it looks like it filters for read size > 18 and change the fastq header line to a counter that is incrementing for each read. Is this the only thing the code does (beside the R plotting)?

Following is my alignment script:

`

#!/bin/bash

export MUGQIC_INSTALL_HOME=/cvmfs/soft.mugqic/CentOS6
module use $MUGQIC_INSTALL_HOME/modulefiles

module add bowtie/1.1.2
module add mugqic/star/2.7.3a
module add bedtools/2.26.0
module add samtools/1.5
module add ascp/3.5.4
#module add sra-toolkit/2.9.6
module add python/3.6.3
module add java/1.8.0_121
module add gcc/5.4.0 r/3.5.0
module rm perl/5.16.3

export __SAMPLE_SHEET__="<TMPL_VAR NAME="SAMPLE_SHEET">"
export __ANN_REF__="<TMPL_VAR NAME="ANN_REF">"
export __RRNA_REF__="<TMPL_VAR NAME="RRNA_REF">"
export __STUDY_NAME__="<TMPL_VAR NAME="STUDY_NAME">"
export __OUTPATH__="<TMPL_VAR NAME="OUTPATH">"
export __SAMPLE_CIT_LIST__="<TMPL_VAR NAME="SAMPLE_CIT_LIST">"
export __BOWTIE_INDEX__="/nfs3_ib/ip32-ib/home/xroucou_group/analysis/price/openprot_1.4/gtf_1.4"
export __RUN_NAME__="<TMPL_VAR name="RUN_NAME">"

if [ -z "$SLURM_TMPDIR" ]
then
    mkdir -p /home/$USER/temp
    SLURM_TMPDIR="/home/$USER/temp"
    echo "\$SLURM_TMPDIR is empty. Will use $SLURM_TMPDIR as temp folder."
else
      echo "Temp folder is $SLURM_TMPDIR"
fi

mkdir -p $SLURM_TMPDIR/$__RUN_NAME__
cd $SLURM_TMPDIR/$__RUN_NAME__

echo "copying programs"
mkdir $SLURM_TMPDIR/${__RUN_NAME__}/programs
#rsync -ah --progress /nfs3_ib/ip32-ib/home/xroucou_group/apps/r_lib_3.5 $SLURM_TMPDIR/${__RUN_NAME__}/programs/
rsync -ah --progress /nfs3_ib/ip32-ib/home/xroucou_group/apps/gedi/build/ $SLURM_TMPDIR/${__RUN_NAME__}/programs/gedi
rsync -ah --progress /nfs3_ib/ip32-ib/home/xroucou_group/apps/Price_1.0.2/reaper-15-065/ $SLURM_TMPDIR/${__RUN_NAME__}/programs/reaper-15-065
rsync -ah --progress /nfs3_ib/ip32-ib/home/xroucou_group/apps/sratoolkit.2.10.4-centos_linux64/ $SLURM_TMPDIR/${__RUN_NAME__}/programs/sratoolkit
rsync -ah --progress /nfs3_ib/ip32-ib/home/xroucou_group/apps/edirect/ $SLURM_TMPDIR/${__RUN_NAME__}/programs/edirect
rsync -ah --progress /nfs3_ib/ip32-ib/home/xroucou_group/apps/jdk/jdk1.8.0_161/ $SLURM_TMPDIR/${__RUN_NAME__}/programs/jdk1.8.0_161
rsync -ah --progress /nfs3_ib/ip32-ib/home/xroucou_group/apps/R $SLURM_TMPDIR/${__RUN_NAME__}/programs/

echo "copying genome"
mkdir $SLURM_TMPDIR/${__RUN_NAME__}/genome
rsync -ah --progress $__BOWTIE_INDEX__/${__RRNA_REF__}.* $SLURM_TMPDIR/${__RUN_NAME__}/genome/
rsync -ah --progress $__BOWTIE_INDEX__/${__ANN_REF__}.* $SLURM_TMPDIR/${__RUN_NAME__}/genome/

#export R_LIBS_USER=$SLURM_TMPDIR/${__RUN_NAME__}/r_lib_3.5
export R_LIBS_USER=/nfs3_ib/ip32-ib/home/xroucou_group/apps/r_lib_3.5
export R_DATATABLE_NUM_PROCS_PERCENT=100
export PATH=/nfs3_ib/ip32-ib/home/xroucou_group/apps/miniconda3/bin:$PATH
export PATH=$SLURM_TMPDIR/${__RUN_NAME__}/programs/gedi:$PATH
export PATH=$SLURM_TMPDIR/${__RUN_NAME__}/programs/reaper-15-065/src:$PATH
export PATH=/cvmfs/soft.computecanada.ca/easybuild/software/2017/sse3/Compiler/intel2016.4/bowtie/1.1.2/bin:$PATH
export PATH=$SLURM_TMPDIR/${__RUN_NAME__}/programs/sratoolkit/bin:$PATH
export PATH=$SLURM_TMPDIR/${__RUN_NAME__}/programs/edirect:$PATH
export PATH=$SLURM_TMPDIR/${__RUN_NAME__}/programs/jdk1.8.0_161/bin:$PATH

export JAVA_HOME=$SLURM_TMPDIR/${__RUN_NAME__}/programs/jdk1.8.0_161
export ALTORF_SCRIPT=/nfs3_ib/ip32-ib/home/xroucou_group/apps/altorf/scripts
export PERL5LIB=/nfs3_ib/ip32-ib/home/xroucou_group/apps_centos7/perl5/lib/perl5
export NCBI_API_KEY=caf7771b1c9c667070db2f515f28addb5908

# echo "fetch run info"
# RUNINFO=$(esearch -db sra -query $__RUN_NAME__ | efetch -format runinfo | awk 'NR>=2' | cut -d "," -f1)
#
# echo "fetch fastq"
# source /nfs3_ib/ip32-ib/home/xroucou_group/apps/miniconda3/etc/profile.d/conda.sh
# conda activate price
# mkdir $SLURM_TMPDIR/${__RUN_NAME__}/tmp_fastq
# mkdir $SLURM_TMPDIR/${__RUN_NAME__}/fastq
# for run in $RUNINFO
# do
#     echo "downloading $run"
#     parallel-fastq-dump --sra-id $run --threads 23 --tmpdir $SLURM_TMPDIR/${__RUN_NAME__}/tmp_fastq --outdir $SLURM_TMPDIR/${__RUN_NAME__}/fastq --split-files
# done
# conda deactivate
#
# cat $SLURM_TMPDIR/${__RUN_NAME__}/fastq/*.fastq > $__RUN_NAME__.fastq
# fastq-dump  -Z $RUNINFO > $__RUN_NAME__.fastq

if [ -f "${__OUTPATH__}/../fastq/${__RUN_NAME__}.fastq" ]
then
    echo "copying fastq ${__RUN_NAME__}.fastq to $SLURM_TMPDIR/${__RUN_NAME__}/"
    #cp ${__OUTPATH__}/../fastq/${__RUN_NAME__}.fastq $SLURM_TMPDIR/${__RUN_NAME__}/
    rsync -ah --progress ${__OUTPATH__}/../fastq/${__RUN_NAME__}.fastq $SLURM_TMPDIR/${__RUN_NAME__}/
else
    echo "${__OUTPATH__}/../fastq/${__RUN_NAME__}.fastq does not exist. Please make sure it is available. Have you run the refetch script?"
    exit 2
fi

echo "Counting all reads"
echo -e "Category\tCount" > $__RUN_NAME__.reads.tsv
echo -ne "All\t" >> $__RUN_NAME__.reads.tsv
L=`wc -l $__RUN_NAME__.fastq | cut -f1 -d' '`
leftreads=$((L / 4))
echo $leftreads >> $__RUN_NAME__.reads.tsv

echo "find adaptor sequence using minion"
head -n4000000 $__RUN_NAME__.fastq > $__RUN_NAME__.head.fastq
minion search-adapter -i $__RUN_NAME__.head.fastq -show 1 -write-fasta adapter.fasta
rm $__RUN_NAME__.head.fastq
ADAPT=`head -n2 adapter.fasta | tail -n1`

echo "cleaning and filtering reads using reaper"
reaper --nozip --noqc -3p-prefix 1/1/0/0 -swp 1/4/4 -geom no-bc -i $__RUN_NAME__.fastq -basename $__RUN_NAME__  -3pa $ADAPT

#export PATH=/nfs3_ib/ip32-ib/home/xroucou_group/apps/R:$PATH
export PATH=$SLURM_TMPDIR/${__RUN_NAME__}/programs/R:$PATH
gedi -e FastqFilter -D -ld $__RUN_NAME__.readlengths.tsv -min 18 $__RUN_NAME__.lane.clean > $__RUN_NAME__.fastq
rm $__RUN_NAME__.lint $__RUN_NAME__.lane.clean

echo -ne "Trimmed\t" >> $__RUN_NAME__.reads.tsv
L=`wc -l $__RUN_NAME__.fastq | cut -f1 -d' '`
leftreads=$((L / 4))
echo $leftreads >> $__RUN_NAME__.reads.tsv

echo "aligning using bowtie on rrna"
bowtie --threads 23 -a -m 100 -v 3 --best --strata --norc --un ${__RUN_NAME__}_unmapped.fastq --sam $SLURM_TMPDIR/${__RUN_NAME__}/genome/${__RRNA_REF__}.genomic $__RUN_NAME__.fastq /dev/null
mv ${__RUN_NAME__}_unmapped.fastq $__RUN_NAME__.fastq
echo -ne "rRNA removal\t" >> $__RUN_NAME__.reads.tsv
leftreads=$( grep -c @ $__RUN_NAME__.fastq )
echo $leftreads >> $__RUN_NAME__.reads.tsv

echo "genomic alignment using bowtie on reference"
bowtie --threads 23 -a -m 100 -v 3 --best --strata   --sam $SLURM_TMPDIR/${__RUN_NAME__}/genome/${__ANN_REF__}.genomic $__RUN_NAME__.fastq $__ANN_REF__.Genomic.sam

echo "samtool sort on genomic alignment"
samtools sort -o $__ANN_REF__.Genomic.sort.sam -n -T $SLURM_TMPDIR/${__RUN_NAME__}/sort -@ 8 -m 1G $__ANN_REF__.Genomic.sam
rm $SLURM_TMPDIR/${__RUN_NAME__}/sort*.bam
mv $__ANN_REF__.Genomic.sort.sam $__ANN_REF__.Genomic.sam
unali=$( grep -v @ $__ANN_REF__.Genomic.sam | cut -f2 | grep -c "^4$" )
echo -ne "$__ANN_REF__(Genomic)\t" >> $__RUN_NAME__.reads.tsv
echo $((leftreads-unali)) >> $__RUN_NAME__.reads.tsv

echo "transcriptomic alignment using bowtie on reference"
bowtie --threads 23 -a -m 100 -v 3 --best --strata --norc  --sam $SLURM_TMPDIR/${__RUN_NAME__}/genome/${__ANN_REF__}.transcriptomic $__RUN_NAME__.fastq ${__ANN_REF__}.Transcriptomic.sam

echo "samtool sort on transcriptomic alignment"
samtools sort -o ${__ANN_REF__}.Transcriptomic.sort.sam -n -T $SLURM_TMPDIR/${__RUN_NAME__}/sort -@ 8 -m 1G ${__ANN_REF__}.Transcriptomic.sam
rm $SLURM_TMPDIR/${__RUN_NAME__}/sort*.bam
mv ${__ANN_REF__}.Transcriptomic.sort.sam ${__ANN_REF__}.Transcriptomic.sam
unali=$( grep -v @ ${__ANN_REF__}.Transcriptomic.sam | cut -f2 | grep -c "^4$" )
echo -ne "${__ANN_REF__}(Transcriptomic)\t" >> $__RUN_NAME__.reads.tsv
echo $((leftreads-unali)) >> $__RUN_NAME__.reads.tsv

mkdir -p $__OUTPATH__/report
echo "gedi mergesam step"
gedi -t . -e MergeSam -D -genomic ${__ANN_REF__} -t $__OUTPATH__/scripts/${__RUN_NAME__}.prio.csv -prio $__OUTPATH__/scripts/${__RUN_NAME__}.prio.oml -chrM -o $__RUN_NAME__.cit
echo -ne "Merged\t" >> $__RUN_NAME__.reads.tsv

echo "gedi Nashorn step"
gedi Nashorn -e "println(EI.wrap(DynamicObject.parseJson(FileUtils.readAllText(new File('$__RUN_NAME__.cit.metadata.json'))).getEntry('conditions').asArray()).mapToDouble(function(d) d.getEntry('total').asDouble()).sum())" >> $__RUN_NAME__.reads.tsv

echo "copying results to $__OUTPATH__"
cp *.readlengths.* $__OUTPATH__/report
cp $__RUN_NAME__.reads.tsv $__OUTPATH__/report

if [ -f "$__RUN_NAME__.cit" ]
then
   cp $__RUN_NAME__.cit* $__OUTPATH__
   #rm -rf $SLURM_TMPDIR/$__RUN_NAME__
else
   echo "There were some errors, will copy temp directory to $__OUTPATH__"
   cp -r * $__OUTPATH__
fi

echo "output R plots"
Rscript $__OUTPATH__/report/${__RUN_NAME__}.reads.R
echo '{"plots":[{"section":"Mapping statistics","id":"mapping'$__RUN_NAME__'","title":"'$__RUN_NAME__'","description":"How many reads are removed by adapter trimming and rRNA mapping, how many are mapped to which reference and retained overall.","img":"'$__RUN_NAME__'.reads.png","script":"'$__RUN_NAME__'.reads.R","csv":"'$__RUN_NAME__'.reads.tsv"}]}' > $__RUN_NAME__.reads.report.json
cp $__RUN_NAME__.reads.report.json $__OUTPATH__/report
echo "done pipeline for $__RUN_NAME__"

`

thanks for your help
JF

**Comment by jflucier** [comment]
I did another check and when I run the mergesam command on multiple compute nodes, I have the exact same problem.

This command hangs forever:

gedi -t . -e MergeSam -D -genomic ${__ANN_REF__} -t $__OUTPATH__/scripts/${__RUN_NAME__}.prio.csv -prio $__OUTPATH__/scripts/${__RUN_NAME__}.prio.oml -chrM -o $__RUN_NAME__.cit

again this is run in the local scratch folder of the compute node.

So I think this problem is in the Gedi engine initialisation and not the specifiac code of fastqfilter or mergesam

thanks
JF

**Comment by jflucier** [comment]
Hi again Florian,

I think I have found the bug with this issue... I replaced all occurent in gedi code where a call to user home directory is made and added the nfs hook ancher to those call. 

I identified the changes to be made using this grep command and edited each reference by adding string ""/nfs3_ib/ip32-ib"+". Then I rebuild the gedi project :

`

|11:14:07|jflucier@ip32-centos7:[openprot_1.4]> grep -re 'System.getProperty("user.home")' /nfs3_ib/ip32-ib/home/xroucou_group/apps/test/gedi
/nfs3_ib/ip32-ib/home/xroucou_group/apps/test/gedi/GediCore/src/gedi/app/Config.java:	private static final String DEFAULT_FOLDER = "/nfs3_ib/ip32-ib"+System.getProperty("user.home")+"/.gedi";
/nfs3_ib/ip32-ib/home/xroucou_group/apps/test/gedi/GediCore/src/jline/internal/Configuration.java:        return new File("/nfs3_ib/ip32-ib"+System.getProperty("user.home"));
/nfs3_ib/ip32-ib/home/xroucou_group/apps/test/gedi/build/src/gedi/app/config/StartCommandConfigurator.java:				String lines = new LineOrientedFile("/nfs3_ib/ip32-ib"+System.getProperty("user.home")+"/.bashrc").readAllText();
/nfs3_ib/ip32-ib/home/xroucou_group/apps/test/gedi/build/src/gedi/app/config/StartCommandConfigurator.java:					LineWriter writer = new LineOrientedFile("/nfs3_ib/ip32-ib"+System.getProperty("user.home")+"/.bashrc").write();
/nfs3_ib/ip32-ib/home/xroucou_group/apps/test/gedi/build/src/gedi/app/Config.java:	private static final String DEFAULT_FOLDER = "/nfs3_ib/ip32-ib"+System.getProperty("user.home")+"/.gedi";
/nfs3_ib/ip32-ib/home/xroucou_group/apps/test/gedi/build/src/net/sf/cglib/TestAll.java:    public static String DEFAULT_DEBUG_LOACATION = "/nfs3_ib/ip32-ib"+System.getProperty("user.home") + 
/nfs3_ib/ip32-ib/home/xroucou_group/apps/test/gedi/build/src/jline/internal/Configuration.java:        return new File("/nfs3_ib/ip32-ib"+System.getProperty("user.home"));
/nfs3_ib/ip32-ib/home/xroucou_group/apps/test/gedi/GediFx/src/gedi/app/config/StartCommandConfigurator.java:				String lines = new LineOrientedFile("/nfs3_ib/ip32-ib"+System.getProperty("user.home")+"/.bashrc").readAllText();
/nfs3_ib/ip32-ib/home/xroucou_group/apps/test/gedi/GediFx/src/gedi/app/config/StartCommandConfigurator.java:					LineWriter writer = new LineOrientedFile("/nfs3_ib/ip32-ib"+System.getProperty("user.home")+"/.bashrc").write();
/nfs3_ib/ip32-ib/home/xroucou_group/apps/test/gedi/cglib/src/net/sf/cglib/TestAll.java:    public static String DEFAULT_DEBUG_LOACATION = "/nfs3_ib/ip32-ib"+System.getProperty("user.home") + 



`

I have run successfully a test running 15 alignement jobs in parralle. Curremtly trying 100. 

Stil currious to know if the fastqfilter step only filters to remove reads <= 18 nt and recode fastq headers with a number. If so I found the follwing awk command to perform better:

`

echo "filtering fastq for size and recoding"
awk '
    BEGIN {
        FS = "\t" ;
        OFS = "\n";
        count = 0;
    }
    {
        count++; header = $0 ; getline seq ; getline qheader ; getline qseq ;
        if (length(seq) >= 18) {
            print "@" count, seq, "+", qseq
        }
    }
' < ${__RUN_NAME__}.lane.clean > ${__RUN_NAME__}.fastq



`

thanks for your help,

JF

**Comment by florianerhard** [comment]
Dear JF,

sorry for not responding for the last few days.

I am not sure how this all connects. If you need to change the value of System.getProperty("user.home"), i suggest to go with java -Duser.home=... instead of patching the code.

Regarding FastqFilter, you are right, at the moment it only does length filtering, length statistics and renaming the reads. It's clear that there are faster ways of doing it, but we would like to keep the flexibility of adding additional filters into this program without changing the pipeline code itself.

Best,
Florian

**Comment by jflucier** [comment]
Hi again, 

the 100 study test failed.... again gedi hangning at the fasqfiltering step.

I used your suggested solution by adding -Duser.home= and -Duser.dir= and still have same issue. 

I changed interactive node where the user home folder is available on comoute nodes using /home/$USER and now pipeline doesnt hang even if I run more then 100 alignements.

I think I get previous hangning of gedi because I am missing some variables (beside user.home and user.dir) that are accessed by gedi code in /home/$USER.... might be linked to logging as the fastqfilter log message dont appear.... 

I thank you for your help, please tell me when you release a new version of gedi where all the gedi variables are read from a config file.

JF
