### ISSUE TITLE
Understanding the .tsv output

### ISSUE THREAD

**Issue by TamaraO** [erhard-lab/price#2]
What do the various columns represent in the output .tsv file? Would these descriptions be accurate?
Column 3: Location - Location of the annotated ORF? 
Column 4: Location of the predicted ORF? 
When columns 3 and 4 are split into multiple segments, are these exons?
Column 5: Start codon?
Column 6: What do the various types mean? In particular, what is Variant? What is orphan? 
Column 7-11: Could you, please, describe what these values are? In particular, for the p value, is there a particular cutoff that you recommend to filter by? 

Thank you!

**Comment by florianerhard** [comment]
Dear Tamara,

I extended the [documentation](https://github.com/erhard-lab/gedi/wiki/Price#using-the-output) on this (which was a bit sparse on the output files, thank you for pointing that out)!

Best,
Florian

**Comment by TamaraO** [comment]
Hi Florian,

For the location vs. candidate location, I expected the bed file to get the final location, from start to stop, but it seems that it outputs the candidate location. But in fact, it's the shorter one, so maybe it's the actual ORF location..? Is it possible that those columns are switched in your doc? 

Thank you,

Tamara
